name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag amitkarpe/tiny:$(date +%s)
    - name: Docker build and push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        repository: amitkarpe/tiny
        tags: amd64
